namespace: elk

stack:
  defines: process-group
  runnable-list:
    - elk/elasticsearch
    # - elk/kibana
    # - elk/logstash
  variables:
    elasticsearch-image-tag: 7.9.0
    jvm-options: "-Xmx256m -Xms256m"
    elasticsearch-http-port: 9200
    elasticsearch-internal-port: 9300

